# Generated by Django 4.1.6 on 2023-05-02 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_textcontent_profilecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
            ],
        ),
        migrations.RemoveField(
            model_name='textcontent',
            name='profile',
        ),
        migrations.AlterField(
            model_name='profilecontent',
            name='profile',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
