# Generated by Django 4.1.6 on 2023-05-03 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_imgcontent_remove_textcontent_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgcontent',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imgcontent',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.user_directory_path),
        ),
    ]
