# Generated by Django 4.1.6 on 2023-05-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_imgcontent_profile_alter_imgcontent_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgcontent',
            old_name='profile',
            new_name='user',
        ),
    ]
