# Generated by Django 4.1.6 on 2023-05-06 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_profile_imgcontent_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='profilecontent',
            name='conttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.contenttype'),
        ),
    ]
