# Generated by Django 4.1.6 on 2023-05-10 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contenttype_alter_profilecontent_conttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgcontent',
            name='user',
        ),
    ]
